### ISSUE TITLE
Stars not displaying on iOS

### ISSUE THREAD

**Issue by tjhunkin-inhance** [geminilabs/star-rating.js#13]
The stars appear on Android devices using Chrome for example.

But using Chrome on iOS, the stars don't appear.

Herewith is a test link: https://merciful-darkness-dwfdh8n3gsef.vapor-farm-d1.com/service/rating

**Comment by pryley** [comment]
This looks like it is specific to your website, likely CSS related. 

The demo site works fine: https://pryley.github.io/star-rating.js/

**Comment by tjhunkin-inhance** [comment]
I decided to replace it
