### ISSUE TITLE
Select second star when clicking outside of stars

### ISSUE THREAD

**Issue by jsongerber** [geminilabs/star-rating.js#19]
Hi, I'm just trying your library and it looks really good, thanks!

I discovered a bug, when clicking outside of a star, the second star get selected.
You can reproduce this bug when clicking on a tooltip in your [demo](https://pryley.github.io/star-rating.js/).

I guess it's coming from [`elementFromPoint`](https://github.com/pryley/star-rating.js/blob/30f18d0945168e23a55bcba39d8ff024360c1bfd/src/widget.js#L125) that resolve to the tag `gl-star-rating--stars` instead of targeting star tags but I'm not sure.

Best,
Jason

**Comment by pryley** [comment]
Thanks. Fixed by disabling pointer-events on pseudo-elements.
