### ISSUE TITLE
Tooltip out of viewport

### ISSUE THREAD

**Issue by davidcmoody** [geminilabs/star-rating.js#20]
When using the star-rating plugin on a small screen, the tooltip ends up off the viewport?

Am I configuring something incorrect?

The ones clearly off the page are in a table cell, the ones below it are just in a div.  But it seems like it doesn't shift the data when the viewport is close?  Or maybe some way to move the tooltip to a different location?

![2023-03-29_17-18-21](https://user-images.githubusercontent.com/25074/228670165-03b627b5-c81c-4c0f-80d5-bd90146b59af.jpg)

**Comment by pryley** [comment]
This is not a bug.

If you need to adjust the tooltip, you have three options:

1. Make your UI responsive to adjust on mobile sizes (i.e. collapse table columns, align ratings left, etc.)
2. Customize the library CSS for the tooltips to suit your page layout.
3. Disable the tooltips.
