### ISSUE TITLE
How to build multiple instances using same class name

### ISSUE THREAD

**Issue by marwan2** [geminilabs/star-rating.js#21]
I can't render multiple select option to Rating stars to be readonly, for being displayed in Listing cards and so on.
Can you show me how do this.

**Comment by marwan2** [comment]
Sorry, I can build it now, but I recommend adding an option "readonly", to be able to display it in website, not only to add/edit new rating.

**Comment by pryley** [comment]
The select element does not support the readonly attribute.

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly

If you want to render a "readonly" star rating, add the disabled attribute to the select element.
