### ISSUE TITLE
Add support for sliding across rating on mobile

### ISSUE THREAD

**Issue by amavaban** [geminilabs/star-rating.js#3]
On desktop if I hold click on a star and then drag the cursor to a different star and release the click then the selected rating will reflect the last star that the cursor was positioned on. This is a nice detail that gives the rating plugin a good sense of responsiveness.

However it does not appear that this behavior works on mobile, where tapping and then sliding across the stars does not register a selection (only a single tap on a star will register a selection).

It would be nice if the aforementioned behavior worked on mobile, allowing users to make adjustments to a rating by sliding their finger rather than having to perform another tap.

Thank you for sharing this plugin- it is my favorite JS rating plugin of the countless that I've looked at!

**Comment by pryley** [comment]
Implemented in v2.2.0
