### ISSUE TITLE
How to use attached events ?

### ISSUE THREAD

**Issue by johndalvik** [geminilabs/star-rating.js#4]
How to use events like change, click, reset etc, and how to get the currently selected star index?

**Comment by pryley** [comment]
1. This library transforms a SELECT element, So just listen for events on the SELECT element. 
2. For reset, listen for the reset event on the form.
3. To get the currently selected star, use [selectedIndex](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/selectedIndex) on the SELECT.
