### ISSUE TITLE
Can we use import statement

### ISSUE THREAD

**Issue by aguidis** [geminilabs/star-rating.js#5]
Hello,

I was just wondering if we could use the es6 `import` statement to load your lib into custom js modules ?

Thanks for this light lib by the way :)

**Comment by pryley** [comment]
I have not tried this.

However, Star Ratings supports CommonJS. If you are using Babel, it converts ES6 import and export declaration to CommonJS (require/module.exports) by default. So even if you use ES6 module syntax, you will be using CommonJS under the hood if you run the code in Node.

```js
const StarRating = require('star-rating.js');

// vs

import StarRating from 'star-rating.js';
```
Please try and let me know.

**Comment by aguidis** [comment]
it works perfectly thank you !
